fixing spark-shell to Spark231

diff --git a/script/spark-shell b/script/spark-shell
--- a/script/spark-shell
+++ b/script/spark-shell
@@ -1,4 +1,11 @@
 #!/bin/bash
-
+cd "$(dirname ${BASH_SOURCE[0]})"/..
+if [ ! -d target ]; then
+   echo "Error: Need to run 'sbt assembly' first"
+   exit 1
+fi
 cd "$(dirname ${BASH_SOURCE[0]})"/../tmp
-spark222/bin/spark-shell --conf "spark.driver.extraClassPath=../target/scala-2.11/classes" --jars `ls ../target/scala-2.11/*assembly*.jar`
+spark231/bin/spark-shell --conf "spark.driver.extraClassPath=../target/scala-2.11/classes" --jars `ls ../target/scala-2.11/*assembly*.jar`;
+if [ $? ]; then
+  echo "*** Make sure you run 'sbt assembly' first ***"
+fi
